name: Manual Recovery

on:
  workflow_dispatch:
    inputs:
      backup:
        description: 'Enter the timestamp of the backup to restore (e.g., Website-Sun-Academy_20230911_123456)'
        required: true
        default: ''

jobs:
  recover:
    runs-on: self-hosted
    steps:
    - name: List backups
      run: |
        echo "Available backups in /opt/backups:"
        ls -l /opt/backups/

    - name: Restore previous version
      run: |
        backup="${{ github.event.inputs.backup }}"
        if [ -d "/opt/backups/$backup" ]; then
          rsync -av --delete /opt/backups/$backup/ /opt/project/Website-Sun-Academy/
          echo "Restored from $backup"
        else
          echo "Backup not found."
        fi

    - name: Restart Docker Compose
      working-directory: /opt/project
      run: |
        docker-compose down
        docker-compose up -d

